src/languages/urls.py
from django.urls import path

from . import views

app_name = "languages"
urlpatterns = [
    # List of languages. (Later, we'll paginate or filter or something.)
    path("", views.languages_home, name="index"),
    # Single language view.
    path("<str:code>/", views.language_detail, name="detail"),

    # Single lexeme view.
    path("<str:code>/<str:text>/", views.lexeme_detail, name="lexeme_detail"),
]

src/pixeme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    # Paths from 3rd party extensions.
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("__reload__/", include("django_browser_reload.urls")),

    # Static handling for uploads.

    # Our paths.
    path("", views.home_page, name="index"),

    # Include paths for each app, too.
    path("image/", include("images.urls")),
    path("lang/", include("languages.urls")),
    path("tags/", include("tags.urls")),
    path("users/", include("users.urls")),
]

# This should be dev-mode only.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tags/urls.py
from django.urls import path

from . import views

app_name = "tags"
urlpatterns = [
    # The main tag page, showing the image, its sentences and audios, and so on.
    path("<str:text>/", views.tag_page, name="tag_page"),

    # HTML partials
]

src/theme/templates/_footer.html
{% load static %}
<footer class="border-t-2 border-neutral bg-neutral pt-2 text-center">
    <nav class="flex flex-wrap justify-center max-w-2xl mx-auto px-8 mb-4 md:mb-2 text-sm">
        <span class="link hover:text-primary px-4 lg:px-6 border-r border-opacity-50 border-neutral-content">
            <a href="{% url "index" %}">Home</a>
        </span>
        <span class="link hover:text-primary px-4 lg:px-6 border-r border-opacity-50 border-neutral-content">
            <a href="#">Terms of Service</a>
        </span>
        <span class="link hover:text-primary px-4 lg:px-6 border-r border-opacity-50 border-neutral-content">
            <a href="#">Privacy Policy</a>
        </span>
        <span class="link hover:text-primary px-4 lg:px-6">
            <a href="#">About</a>
        </span>
    </nav>
    <small>
        <p>© {% now "Y" %} The Pixeme Project. All rights reserved. User-generated content is the property of its creators.</p>
    </small>
    <div class="min-h-2">
        <!-- Social icons -->
    </div>
</footer>

src/theme/templates/_footer.jinja
<footer class="border-t-2 border-neutral bg-neutral pt-2 text-center">
    <nav class="flex flex-wrap justify-center max-w-2xl mx-auto px-8 mb-4 md:mb-2 text-sm">
        <span class="link hover:text-primary px-4 lg:px-6 border-r border-opacity-50 border-neutral-content">
            <a href="{{ url('index') }}">Home</a>
        </span>
        <span class="link hover:text-primary px-4 lg:px-6 border-r border-opacity-50 border-neutral-content">
            <a href="#">Terms of Service</a>
        </span>
        <span class="link hover:text-primary px-4 lg:px-6 border-r border-opacity-50 border-neutral-content">
            <a href="#">Privacy Policy</a>
        </span>
        <span class="link hover:text-primary px-4 lg:px-6">
            <a href="#">About</a>
        </span>
    </nav>
    <small>
        <p>© {{ now().year }} The Pixeme Project. All rights reserved. User-generated content is the property of its creators.</p>
    </small>
    <div class="min-h-2">
        <!-- Social icons -->
    </div>
</footer>

src/theme/templates/_navbar.html
{% load static %}
<nav class="navbar bg-base-100">
    <div class="navbar-start">
        <div class="dropdown">
            <button type="button" class="btn btn-ghos">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="currentColor" stroke="none" viewBox="0 0 24 24"><title>menu</title><path d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" /></svg>
            </button>
            <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                <li><a href={% url "index" %}>Home</a></li>
                <li><a href="{% url "languages:index" %}">Languages</a></li>
            </ul>
        </div>
        <a href="{% url "index" %}">
            <img src="{% static "img/pixeme-logo.svg" %}" alt="Pixeme logo" class="h-8">
        </a>
    </div>
    <div class="navbar-end">
        {% if user.is_authenticated %}
        <div class="dropdown">
            <button type="button" class="btn btn-ghost font-normal">You are logged in as <strong>{{ user.username }}</strong></button>
            <ul class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box">
                <li><a href="#">Profile</a></li>
                <hr class="my-2 border-neutral">
                <li><a href="{% url "account_logout" %}"
                    hx-push-url="{% url "index" %}"
                    hx-post="{% url "account_logout" %}"
                    hx-target="body"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    >Sign Out</a></li>
            </ul>
        </div>
        {% else %}
        <a href="{% url "account_login" %}" class="px-2 md:px-4 btn btn-ghost">Sign In</a>
        <a href="{% url "account_signup" %}"
            class="px-2 md:px-4 btn btn-ghost">Sign Up</a>
        {% endif %}
    </div>
</nav>

src/theme/templates/_navbar.jinja
<nav class="navbar bg-base-100">
    <div class="navbar-start">
        <div class="dropdown">
            <button type="button" class="btn btn-ghos">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="currentColor" stroke="none" viewBox="0 0 24 24"><title>menu</title><path d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" /></svg>
            </button>
            <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                <li><a href="{{ url('index') }}">Home</a></li>
                <li><a href="{{ url('languages:index') }}">Languages</a></li>
            </ul>
        </div>
        <a href="{{ url('index') }}">
            <img src="{{ static('img/pixeme-logo.svg') }}" alt="Pixeme logo" class="h-8">
        </a>
    </div>
    <div class="navbar-end">
        {% if user.is_authenticated %}
        <div class="dropdown">
            <button type="button" class="btn btn-ghost font-normal">You are logged in as <strong>{{ user.username }}</strong></button>
            <ul class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box">
                <li><a href="#">Profile</a></li>
                <hr class="my-2 border-neutral">
                <li><a href="{{ url('account_logout') }}"
                    hx-push-url="{{ url('index') }}"
                    hx-post="{{ url('account_logout') }}"
                    hx-target="body"
                    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                    >Sign Out</a></li>
            </ul>
        </div>
        {% else %}
        <a href="{{ url('account_login') }}" class="px-2 md:px-4 btn btn-ghost">Sign In</a>
        <a href="{{ url('account_signup') }}"
            class="px-2 md:px-4 btn btn-ghost">Sign Up</a>
        {% endif %}
    </div>
</nav>

src/theme/templates/base.html
{% load tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %}Pixeme{% endblock title %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}

		<script src="{% static 'js/htmx.min.js' %}" defer></script>
		<script src="{% static "js/surreal.js" %}"></script>
		{% block scripts %}{% endblock scripts %}
	</head>

	<body class="flex flex-col min-h-[100vh]">
		<header class="flex-shrink">
		{% include "_navbar.html" %}
		</header>

		{% block header %}{% endblock header %}

		<main class="py-2 px-4 md:px-6 flex-grow">
			{% block content %}{% endblock content %}
		</main>

		{% block footer %}
			{% include "_footer.html" %}
		{% endblock footer %}
	</body>
</html>

src/theme/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %}Pixeme{% endblock title %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{# {% tailwind_css %} #}
        <link rel="stylesheet" href="{% if tailwind.is_static_path %}{{ static(tailwind.css_path) }}{% else %}{{ tailwind.css_path }}{% endif %}{% if v %}?v={{ v }}{% endif %}">

		<script src="{{ static('js/htmx.min.js') }}" defer></script>
		<script src="{{ static('js/surreal.js') }}"></script>
		{% block scripts %}{% endblock scripts %}
	</head>

	<body class="flex flex-col min-h-[100vh]">
		<header class="flex-shrink">
		{% include "_navbar.jinja" %}
		</header>

		{% block header %}{% endblock header %}

		<main class="py-2 px-4 md:px-6 flex-grow">
			{% block content %}{% endblock content %}
		</main>

		{% block footer %}
			{% include "_footer.jinja" %}
		{% endblock footer %}
	</body>
</html>